### ISSUE TITLE
Apprentice exercise 7 will not run as written

### ISSUE THREAD

**Issue by ghevcoul** [rougier/numpy-100#1]
The scipy comparison will not run as written and throws an AttributeError on the line `D = scipy.spatial.distance.cdist(Z,Z)`. To resolve this, you need to `import scipy.spatial` on the previous line.

**Comment by rougier** [comment]
Oh, thanks. Can you write a PR (to appear in the contributors) ?

**Comment by rougier** [comment]
Corrected, thanks.
