### ISSUE TITLE
It seems that #61 and #50 are similar

### ISSUE THREAD

**Issue by ToheartZhang** [rougier/numpy-100#139]
> 61. Find the nearest value from a given value in an array (★★☆)

> 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

**Comment by rougier** [comment]
You're right. We should merge them and find a new question for 61. Maybe something like find the 3 nearest values and we could use partial ordering to speed things up.

**Comment by ToheartZhang** [comment]
> 
> 
> You're right. We should merge them and find a new question for 61. Maybe something like find the 3 nearest values and we could use partial ordering to speed things up.

Thx for replying!

**Comment by rougier** [comment]
Do you want to write the new 61 ?

**Comment by ToheartZhang** [comment]
> 
> 
> Do you want to write the new 61 ?

Sure, I'll try to make a pull request.
