### ISSUE TITLE
'numpy.ndarray' object has no attribute 'random'

### ISSUE THREAD

**Issue by coco202222** [rougier/numpy-100#168]
Hello, does anyone know how to fix this attribute error?

In [34]: np.random.randint(0,100,size=(5,3))
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-482b267cda3e> in <module>
----> 1 np.random.randint(0,100,size=(5,3))

AttributeError: 'numpy.ndarray' object has no attribute 'random'

**Comment by rougier** [comment]
What is `np` in you case? If you first `import numpy as np`, does it fail too?

**Comment by coco202222** [comment]
> What is `np` in your session? If you first `import numpy as np`, does it fail too?

thanks i got it!
