### ISSUE TITLE
Fail to load the ipython notebook

### ISSUE THREAD

**Issue by robeatnik** [rougier/numpy-100#19]
Hi, I got something wrong with the ipython notebook in [Binder](http://mybinder.org/repo/rougier/numpy-100/notebooks/100%20Numpy%20exercises.ipynb).

what I got:
![2016-08-31 22 13 31](https://cloud.githubusercontent.com/assets/16472935/18132249/a3ad519c-6fc8-11e6-8f61-873a01d0f253.png)

and when I opened the 100 numpy exercises.ipynb file with my ipython I got the same error.
my ipython version: 4.2.1

**Comment by rougier** [comment]
I confirm, I just get the same error. I think commit 9b248dd3de65802e472501c745f1069f4560df77 is responsible for the problem (PR #17 byt @ibah ). I'll revert to previous state.

**Comment by rougier** [comment]
Should be fixed now. 

@ibah can you submit new PR? (I've cancelled your PR due to the problem mentioned above)

**Comment by robeatnik** [comment]
Thank you! 
:)

**Comment by ibah** [comment]
Hi, I submitted the new PR. I checked the notebook for errors - should be OK this time.

**Comment by robeatnik** [comment]
Thanks a lot!
:)
