### ISSUE TITLE
Typo: 86. ... matrices wich shape ... -> ... matrices with shape ...

### ISSUE THREAD

**Issue by jeremy-feng** [rougier/numpy-100#195]
There may be a typo in question 86:

[Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1).](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md#LL1016C10-L1016C96)

I think 'wich' should be 'with'.

**Comment by rougier** [comment]
Thanks, you're right. Can you make a PR (in the .ktx files)?

**Comment by jeremy-feng** [comment]
> Thanks, you're right. Can you make a PR (in the .ktx files)?

Sure. I have fixed it and rerun `generators.py`. Please review the [PR](https://github.com/rougier/numpy-100/pull/196).
