### ISSUE TITLE
Alternative solution to q4

### ISSUE THREAD

**Issue by jeremy-feng** [rougier/numpy-100#197]
Use `Z.nbytes` to find the memory size directly.

```python
print("%d bytes" % (Z.nbytes))
```

**Comment by rougier** [comment]
Thanks. Can you make a PR (adding your line below the current one)? Also, make sure to only modify the kth files since others are generated.

**Comment by jeremy-feng** [comment]
Already solved in https://github.com/rougier/numpy-100/issues/157.
