### ISSUE TITLE
Q.83 - `np.bincount` doesn't work on negative values

### ISSUE THREAD

**Issue by iamyifan** [rougier/numpy-100#204]
Hi @rougier,

Q.83 asks `How to find the most frequent value in an array?`
And the current answer is:
``` python
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())
```

The document says `np.bincount` can only count nonnegative ints in 1-dimension arrays, which is not universal and not helpful in some scenarios.

A possible solution will be:
``` python
Z = np.random.randint(0, 10, 50)
# returns the sorted unique elements and their corresponding counts
uniq_vals, counts = np.unique(Z, return_counts=True)
most_freq_val = uniq_vals[counts.argmax()]
print(most_freq_val)
```

Cheers,
@iamyifan

**Comment by rougier** [comment]
Thanks. For generic case, you can use `np.bincount(Z-Z.min()).argmax()`

**Comment by nirbar8** [comment]
Hi @rougier, I agree with @iamyifan solution since it's more suitable in the case of large values, and also works for floats.
