### ISSUE TITLE
Solution to "How to find rows of A that contain elements of each row of B" exercise

### ISSUE THREAD

**Issue by ibah** [rougier/numpy-100#32]
Hi,
It seems the solution given is wrong unless I misunderstood the question. The question is:

> Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A
that contain elements of each row of B regardless of the order of the elements in B?

The solution provided selects rows of A that contain (1) at least two unique elements of B (can be the same unique element of B repeated twice)  or (2) at least one element that occurs 2 or more times in B. The rows of B are irrelevant. This seems not to answer the question correctly.
Example:
```
B = np.array([[0,1],[2,2]])
A = np.array([[3,3,3],[0,1,3],[0,0,3],[1,1,3],[2,3,3],[0,2,3],[1,2,3]])
```
The correct solution should pick rows of A that contains 0 and 2 or 1 and 2 (i.e. each row of B is represented in a given row of A) - so only rows 5 an 6.
Current solution will also pick rows of A that contain [0,1], 2x 0, 2x 1 or 1x 2 - so rows 1,2,3,4.
```
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)
```
```
[1 2 3 4 5 6]
```

The correct solution could be:
```
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)
```
```
[5 6]
```

**Comment by ibah** [comment]
Sorry, I don't know how to break lines inside the code blocks - tried many things, didn't work.

**Comment by rougier** [comment]
Triple quote is your friend ! I edited your comment, hope you don't mind.

**Comment by ibah** [comment]
Thanks for fixing the comment.

**Comment by rougier** [comment]
Thanks, you're right about your modificiation. Could make a PR ?

**Comment by ibah** [comment]
Yes, I will make the PR.
