### ISSUE TITLE
the 5th question's solution doesn't work.

### ISSUE THREAD

**Issue by mgdreamingstar** [rougier/numpy-100#45]
%run `python -c "import numpy; numpy.info(numpy.add)"`

It yields:
```
ERROR:root:File `u'`python.py'` not found.
```

**Comment by rougier** [comment]
Weird. How do you start a regular python session from the terminal?

**Comment by mgdreamingstar** [comment]
just type the 'python' command in cmd.exe

**Comment by mgdreamingstar** [comment]
in the cmd.exe, this line work:
`python -c "import numpy; numpy.info(numpy.add)"`

**Comment by mgdreamingstar** [comment]
I'm wondering why the `%run` command doesn't recognize this command line as a line of python code.

**Comment by rougier** [comment]
Oh, the line is supposed to be `python -c "import numpy; numpy.info(numpy.add)"` without the run actually.

**Comment by mgdreamingstar** [comment]
You mean in the jupyter notebook?

**Comment by rougier** [comment]
No, on the terminal.

**Comment by mgdreamingstar** [comment]
ok, yet don't know how to run it in jupyter notebook. Thanks for your patience anyway.

**Comment by rougier** [comment]
From within Jupyter (or python session):

```
import numpy
numpy.info("add")
```

**Comment by mgdreamingstar** [comment]
thank you! maybe the answer doesn't work for me.

**Comment by g-morishita** [comment]
I think %run is wrong. You should replace %run with "!" if you want to run a shell command within Jupyter, which may be useless.

**Comment by chanqi4444** [comment]
also this problem,  @mgdreamingstar 
Input :
```
%run `python -c "import numpy; numpy.info(numpy.add)"`
```
Error :
```
ERROR:root:File `'`python.py'` not found.
```
the IPython built-in magic command `%run` can't recognize `python` as a program (because it automatically looks for 'python.py'), so you can change this into `!` which works for me. 

```
!python -c "import numpy; numpy.info(numpy.add)"
```
