### ISSUE TITLE
Better way to do solve no. 9

### ISSUE THREAD

**Issue by sominwadhwa** [rougier/numpy-100#49]
`p = np.random.randint(9, size=(3,3))`

Saves the overhead of reshaping.

**Comment by rougier** [comment]
Are you referring to "9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)"?
I think your solution is not equivalent, is it?

**Comment by sominwadhwa** [comment]
@rougier I think it is. It does output the same result- 3 x 3 matrix (in randomized manner), where values may/may not be unique (but strictly in the specified range. Please let me know otherwise?

`Z = np.arange(9).reshape(3,3)` will provide a sorted matrix.

**Comment by rougier** [comment]
Maybe I badly wrote the question. In my mind,  you need to have all values from 0 to 8. I used "ranged" with reference to the `arange` method, maybe this the confusing part:
```
>>> print (np.arange(9).reshape(3,3))
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

**Comment by sominwadhwa** [comment]
Ah, I see. I thought otherwise. No issues :)
