### ISSUE TITLE
20 - solution returns index of 101st element

### ISSUE THREAD

**Issue by greenovid** [rougier/numpy-100#54]
In question 20, it is assumed that the 100th element is at index 100, which is inconsistent with question 6, where the 5th element is assumed to be at index 4.

**Comment by rougier** [comment]
You're right. Can you provide a PR ?

**Comment by SebastianoF** [comment]
An option could be changing the answer in:

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
```python
np.unravel_index(99, (6,7,8))
```

**Comment by rougier** [comment]
You're right. Could you make a PR?

**Comment by quq99** [comment]
in .pynb file it is still `np.unravel_index(100, (6,7,8))`

**Comment by rougier** [comment]
@quq99 Can you make a PR?

**Comment by Renelvon** [comment]
This issue has been fixed. Maybe close it? :)
