### ISSUE TITLE
#53 IS BACKWARDS

### ISSUE THREAD

**Issue by MikeBloom914** [rougier/numpy-100#56]
The question asks how to convert a FLOAT into an INTEGER however the answer is written as if you were to convert an INTEGER into a FLOAT.  So either the question should be reversed, or the answer to the problem should be reversed.

<img width="587" alt="showing error on 53" src="https://user-images.githubusercontent.com/34034720/36286956-158e0008-1280-11e8-90e1-b73a0545406f.png">

**Comment by rougier** [comment]
You're right. Can you make a PR to correct the problem?

**Comment by MikeBloom914** [comment]
Sure!
