### ISSUE TITLE
Problem #22. Different from actual definition of Normalization

### ISSUE THREAD

**Issue by nithinraok** [rougier/numpy-100#67]
Normalization theoretically means subtracting by mean and dividing by standard deviation so that overall data has zero mean and unit variance.

So the code becomes 
```python
Z=np.random.random((5,5));
a=(Z-np.mean(Z))/(np.std(Z))
print(a)
```

**Comment by lexnekr** [comment]
I think you're right about normalization.

https://en.wikipedia.org/wiki/Normalization_(statistics)

The task now uses the formula not "normalization", but "Feature scaling"

P.S. I created pull request.

**Comment by nithinraok** [comment]
Looks good to me 👍

**Comment by Yossarian0916** [comment]
`a=(Z - Z.mean()) / Z.std()` should actually be called standardization and z-score, 
`a=(Z - Z.mean()) / (Z.max() - Z.min())` is the feature scaling and normalization
