### ISSUE TITLE
96. unique rows

### ISSUE THREAD

**Issue by kuzand** [rougier/numpy-100#68]
It can be done directly by numpy `unique` function specifying the axis
 `np.unique(Z, axis=0)`

**Comment by rougier** [comment]
Thanks. Much simpler actually. Can you make a PR ?

**Comment by kuzand** [comment]
Ok, did it. By the way, I cannot open the 100_Numpy_exercises.ipynb file. I get the following error: NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)

**Comment by rougier** [comment]
You mean you cannot open it with jupyter notebook ?
