### ISSUE TITLE
Jupyter notebook files are not opening

### ISSUE THREAD

**Issue by kuzand** [rougier/numpy-100#71]
When I try to view the .ipynb files on GitHub:
```
100_Numpy_exercises.ipynb
100_Numpy_exercises_with_hint.ipynb
```

I get the error 

> Sorry, something went wrong. Reload?

I also tried to view them on https://nbviewer.jupyter.org/ but without success either:
https://nbviewer.jupyter.org/github/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb
https://nbviewer.jupyter.org/github/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hint.ipynb

> Error reading JSON notebook

Same when running locally on my computer.

Note: 100_Numpy_exercises_no_solution.ipynb is opening without problem.

**Comment by rougier** [comment]
Yes, same here. Probably a commit corrupted them at some point but I'm so good at `git bisect` to find it.
