### ISSUE TITLE
Why can we normalize an array in the way that No.22 do?

### ISSUE THREAD

**Issue by yiran7324** [rougier/numpy-100#75]
I know what `np.mean()` does and the process of `np.std()`, but I couldn't figure out why we can do a normalization in the way that combine them together.

Why does it works normalize an array like `Z = (Z - np.mean (Z)) / (np.std (Z))`  use dividing?

**Comment by rougier** [comment]
Did you find the answer?

**Comment by yiran7324** [comment]
It's just a formula in math [here](https://en.wikipedia.org/wiki/Normalization_(statistics)), and doesn't have much to do with numpy.
