### ISSUE TITLE
Simpler solution for Q.25

### ISSUE THREAD

**Issue by chitraanshpopli** [rougier/numpy-100#76]
25. Given a 1D array, negate all elements which are between 3 and 8, in place. 

Current solution:
```
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)
```

Cleaner solution:
```
Z = np.arange(11)
Z[3:9] *= -1
print(Z)
```

**Comment by rougier** [comment]
I think your solution is not the same. You are inverting elements whose index is between 3 and 8 while we want to do that for values.

**Comment by chitraanshpopli** [comment]
Oh alright, I misunderstood the question.
