### ISSUE TITLE
rougier/numpy-100 exercise - Que 16. alternate solution

### ISSUE THREAD

**Issue by sudhendra-github** [rougier/numpy-100#85]
16. How to add a border (filled with 0's) around an existing array? (★☆☆)¶

**Proposed Solution -** 

a=np.random.randint(1,10,(5,5))
print(a)
a[0:,(0,-1)]=0
a[(0,-1),1:-1]=0
print(a)

Pl. give feedback on this, I am new to Python.

**Comment by rougier** [comment]
Sorry for the delay. You solution is nice. Can you make a PR and add it as "alternative method" ?

**Comment by acharles7** [comment]
fancier and more readable
```
a = np.random.randint(1, 10, (5, 5))
a[:, [0, -1]] = 0
a[[0, -1], :] = 0
print(a)
```
Please let me know if you want PR as  "alternative method" ?

**Comment by rougier** [comment]
@acharles7 Thanks. Let's first see if @sudhendra-github would like to make a PR

**Comment by acharles7** [comment]
@rougier Can I start working on this?

**Comment by rougier** [comment]
Ok
