### ISSUE TITLE
About No.25

### ISSUE THREAD

**Issue by martin-lee07** [rougier/numpy-100#93]
Given a 1D array, negate all elements which are between 3 and 8, in place

the code is 
`Z[(3 < Z) & (Z <= 8)] *= -1`

and according to the title that "### **between 3 and 8, in place**",shouldn't it is 
`Z[(3 < Z) & (Z < 8)] *= -1`? without `=`  because between 3 and 8 is 4,5,6,7 these four elements?

**Comment by rougier** [comment]
You're right, I should have said 3 and 8 excluded and use your proposed fix. Can you make a PR?

**Comment by prakharb10** [comment]
Hi, can I help you with this?

**Comment by rougier** [comment]
Let's see if @martin-lee07 want to make the PR first.

**Comment by acharles7** [comment]
@rougier Can I make PR for this?
